server {
    listen 80;
    server_name shikii.dev;
    root /usr/share/nginx/html;
    index index.html;

    location = /config.js {
        add_header Cache-Control "no-store, no-cache, must-revalidate" always;
        add_header Pragma "no-cache" always;
        expires off;
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
