services:
  frontend:
    image: shikihtm/notes-app-frontend:latest
    container_name: notes-app-frontend
    restart: unless-stopped
    networks:
      - notes-network

  backend:
    image: shikihtm/notes-app-backend:latest
    container_name: notes-app-backend
    restart: unless-stopped
    working_dir: /var/www
    env_file:
      - .env
    networks:
      - notes-network
    depends_on:
      - db
      - redis

  webserver:
    build:
      context: .
      dockerfile: ./backend/docker/nginx.Dockerfile
    container_name: notes-app-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - notes-network
    depends_on:
      - backend
      - frontend

  db:
    image: mysql:8.0
    container_name: notes-app-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - notes-network

  redis:
    image: redis:alpine
    container_name: notes-app-redis
    restart: unless-stopped
    networks:
      - notes-network

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run --protocol http2 --token ${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - notes-network

  hocuspocus:
    image: shikihtm/notes-app-yjs:latest
    container_name: notes-yjs-server
    restart: unless-stopped
    networks:
      - notes-network

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: notes-app-meilisearch
    restart: unless-stopped
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
      MEILI_ENV: production
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - notes-network

networks:
  notes-network:
    driver: bridge

volumes:
  dbdata:
  meilisearch_data:
